export enum AppLogSourceDirectory {
    APP_FORM_SERVICE =  <any>'APP_FORM_SERVICE',
    APP_INFO_SERVICE = <any>'APP_INFO_SERVICE',
    APP_LOG_SERVICE = <any>'APP_LOG_SERVICE',
    APP_STATE_SERVICE = <any>'APP_STATE_SERVICE',
    APP_TRANSLATE_SERVICE = <any>'APP_TRANSLATE_SERVICE',

    USER_SERVICE = <any>'USER_SERVICE',

    LOGIN_COMPONENT = <any>'LOGIN_COMPONENT',
}